version: '3.3'
services:
  front:
    build: url-shortener-front
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - API_URL=http://api:8080/api/urls
      - REACT_APP_API_URL=http://api:8080/api/urls
  api:
    build: url-shortener-api
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=RedisStorage
      - SPRING_REDIS_HOST=redis
  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes